# Generated by Django 4.2.7 on 2023-11-12 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=6)])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('Admin', 'Administrador'), ('Intendente', 'Intendencia')], max_length=12)),
                ('edificio', models.CharField(blank=True, max_length=50, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nombres'],
            },
        ),
    ]
