# Generated by Django 3.2.19 on 2023-11-07 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=6)])),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(limit_value=8)])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('rol', models.CharField(choices=[('Admin', 'Administrador'), ('Intendente', 'Intendencia')], max_length=12)),
                ('edificio', models.CharField(blank=True, max_length=50, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
