# Generated by Django 4.2.7 on 2023-11-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='Origen',
            field=models.CharField(choices=[('Unison', 'Unison'), ('Exterior', 'Exterior')], max_length=8, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='material',
            name='cantidad_limite',
            field=models.IntegerField(verbose_name='Cantidad límite'),
        ),
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.CharField(choices=[('Electrico', 'Electrico'), ('Plomeria', 'Plomeria'), ('Limpieza', 'Limpieza'), ('Oficina', 'Oficina')], max_length=10, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='material',
            name='imagen',
            field=models.ImageField(default='Pendiente', upload_to='', verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre_articulo',
            field=models.CharField(max_length=50, verbose_name='Nombre de artículo'),
        ),
        migrations.AlterField(
            model_name='material',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
