# Generated by Django 4.2.7 on 2023-11-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_alter_material_origen_alter_material_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='cantidad_limite',
        ),
        migrations.AddField(
            model_name='material',
            name='umbral',
            field=models.IntegerField(default=20, verbose_name='Umbral mínimo'),
            preserve_default=False,
        ),
    ]
