# Generated by Django 4.2.7 on 2023-11-12 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_remove_material_cantidad_limite_material_umbral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gasto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material', verbose_name='Material')),
            ],
        ),
    ]
