# Generated by Django 4.2.7 on 2023-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gasto',
            name='fecha',
            field=models.DateField(auto_now=True, verbose_name='Fecha de gasto'),
        ),
    ]
