# Generated by Django 4.2.7 on 2023-11-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0007_alter_carrito_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
