# Generated by Django 4.2.7 on 2023-11-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0008_carrito_confirmado_alter_carrito_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='gasto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gasto'),
        ),
    ]
