# Generated by Django 4.2.7 on 2023-11-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0009_alter_gasto_cantidad_alter_gasto_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
    ]
