# Generated by Django 4.2.7 on 2023-11-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_reporte_estado_alter_reporte_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.CharField(default='Quedan pocos artículos', max_length=22, verbose_name='Descripción'),
        ),
    ]
