# Generated by Django 4.2.7 on 2023-11-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_alter_reporte_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='descripcion',
            field=models.CharField(choices=[('Ya no hay artículos', 'Producto Acabado'), ('Quedan pocos artículos', 'Producto Escaso')], default='Quedan pocos artículos', max_length=22, verbose_name='Descripción'),
        ),
    ]
